version: "3"

services:
  backend:
    build: ./backend
    ports:
      - 80:80
      - 443:443
  frontend:
    build: ./frontend/main
    ports:
      - 3000:3000
  database:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
